[package]
name = "dfdx"
version = "0.7.0"
edition = "2021"
license = "MIT OR Apache-2.0"

description = "Ergonomic auto differentiation in Rust, with pytorch like apis."
homepage = "https://github.com/coreylowman/dfdx"
documentation = "https://docs.rs/dfdx"
repository = "https://github.com/coreylowman/dfdx"
readme = "README.md"

keywords = [
    "deep-learning",
    "neural-network",
    "backprop",
    "tensor",
    "autodiff",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
matrixmultiply = "0.3.2"
num-traits = "0.2.15"
zip = "0.6.2"
cblas-sys = { version = "0.1.4", optional = true }
libc = { version = "0.2.126", optional = true }

[features]
default = ["intel-mkl", "mkl-dynamic-lp64-iomp"]
intel-mkl = ["dep:cblas-sys", "dep:libc"]
mkl-static-lp64-iomp = []
mkl-static-lp64-seq = []
mkl-static-ilp64-iomp = []
mkl-static-ilp64-seq = []
mkl-dynamic-lp64-iomp = []
mkl-dynamic-lp64-seq = []
mkl-dynamic-ilp64-iomp = []
mkl-dynamic-ilp64-seq = []

[dev-dependencies]
tempfile = "3.3.0"
mnist = "0.5.0"
indicatif = "0.16.2"